name: Deploy Stack on AWS
on:
  push:
    branches:
      - main

jobs: # jobs to run on azure pool created by actions
  ec2-deploy:

    runs-on: ubuntu-latest
    needs: s3-deploy

    steps:

    - name: setup node.js 20 version
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: checkout code
      uses: actions/checkout@v2

    - name: list code dir
      run: ls

    - name: install dependencies
      run: |
        cd ds-day4-bestway
        npm install
        npm install -g aws-cdk
        
    - name: compile code
      run: |
        cd ds-day4-bestway
        cdk synth

    - name: deploy cdk in aws account
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        cd ds-day4-bestway/
        cdk deploy DsDay4ec2allStack --require-approval never

  s3-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: setup node.js 20 version
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: checkout code
      uses: actions/checkout@v2

    - name: list code dir
      run: ls

    - name: install dependencies
      run: |
        cd ds-day4-bestway
        npm install
        npm install -g aws-cdk
        
    - name: compile code
      run: |
        cd ds-day4-bestway
        cdk synth

    - name: deploy cdk in aws account
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        cd ds-day4-bestway/
        cdk deploy DsDay4BestwayStack --require-approval never
    
  # job2:
  # job3:
